import type { Category, Collection, Product, ProductType, Variant } from '../../packages/types/src/index.ts'
import { isoDaysAgo } from './master.ts'
import { rng } from './rng.ts'

interface ProductSeed {
  name: string
  cat: string
  price: number
  type?: ProductType
  compareAt?: number
  sizes?: 'shoe' | 'apparel' | 'shade' | 'volume' | 'none' | 'spec'
  tags?: string[]
  best: string
  desc: string
  assisted?: boolean
  status?: Product['status']
  /** Relative sales weight. */
  pop?: number
}

type CategorySeed = Omit<Category, 'tenantId'>
const C = (id: string, name: string, description: string, parentId: string | null = null): CategorySeed => ({
  id,
  name,
  description,
  parentId,
})

const CATEGORIES: Record<string, CategorySeed[]> = {
  'ten-lari': [
    C('cat-lari-shoes', 'Shoes', 'Every running shoe, road and trail.'),
    C('cat-lari-road', 'Road running shoes', 'Daily trainers, tempo shoes and racers.', 'cat-lari-shoes'),
    C('cat-lari-trail', 'Trail shoes', 'Grip and protection for dirt and rock.', 'cat-lari-shoes'),
    C('cat-lari-apparel', 'Apparel', 'Tees, shorts, tights and jackets.'),
    C('cat-lari-acc', 'Accessories', 'Socks, caps, belts, vests and watches.'),
    C('cat-lari-nutri', 'Nutrition', 'Gels, electrolytes and recovery.'),
    C('cat-lari-coach', 'Coaching & events', 'Plans, gait analysis and coaching.'),
  ],
  'ten-aruna': [
    C('cat-aruna-face', 'Face', 'Skincare and makeup for the face.'),
    C('cat-aruna-skin', 'Skincare', 'Cleansers, serums, moisturisers and SPF.', 'cat-aruna-face'),
    C('cat-aruna-makeup', 'Makeup', 'Base, lips, brows and cheeks.', 'cat-aruna-face'),
    C('cat-aruna-hair', 'Haircare', 'Scalp care and styling oils.'),
    C('cat-aruna-frag', 'Fragrance', 'Eau de parfum.'),
    C('cat-aruna-sets', 'Gift sets', 'Bundles, consultations and the monthly box.'),
  ],
  'ten-teknika': [
    C('cat-tek-machines', 'Machines', 'Capital equipment sold through sales.'),
    C('cat-tek-cnc', 'CNC machines', 'Machining centers and lathes.', 'cat-tek-machines'),
    C('cat-tek-air', 'Compressed air', 'Compressors and dryers.', 'cat-tek-machines'),
    C('cat-tek-parts', 'Spare parts', 'Filters, bearings, oils and tooling.'),
    C('cat-tek-service', 'Service contracts', 'Preventive service and commissioning.'),
  ],
}

const P = (s: ProductSeed) => s

const SEEDS: Record<string, ProductSeed[]> = {
  'ten-lari': [
    P({
      name: 'Velocity Pro 3',
      cat: 'cat-lari-road',
      price: 2_499_000,
      sizes: 'shoe',
      tags: ['carbon plate', 'race'],
      best: 'Half and full marathon racing',
      desc: 'Carbon-plated racer with a PEBA foam stack.',
      pop: 9,
    }),
    P({
      name: 'Velocity Trainer',
      cat: 'cat-lari-road',
      price: 1_499_000,
      compareAt: 1_699_000,
      sizes: 'shoe',
      tags: ['daily trainer'],
      best: 'Daily miles and 10K training',
      desc: 'Cushioned daily trainer for easy and tempo runs.',
      pop: 14,
    }),
    P({
      name: 'Swift 5K',
      cat: 'cat-lari-road',
      price: 899_000,
      sizes: 'shoe',
      tags: ['beginner'],
      best: 'New runners up to 10K',
      desc: 'Light, forgiving shoe for your first 5K.',
      pop: 16,
    }),
    P({
      name: 'Cloudstep Max',
      cat: 'cat-lari-road',
      price: 1_899_000,
      sizes: 'shoe',
      tags: ['max cushion'],
      best: 'Long slow runs and recovery days',
      desc: 'Maximum cushion for long Sundays.',
      pop: 10,
    }),
    P({
      name: 'Tempo Flyer',
      cat: 'cat-lari-road',
      price: 1_299_000,
      sizes: 'shoe',
      tags: ['tempo'],
      best: 'Intervals and tempo sessions',
      desc: 'Snappy midsole for speed work.',
      pop: 8,
    }),
    P({
      name: 'Stability Guide 2',
      cat: 'cat-lari-road',
      price: 1_599_000,
      sizes: 'shoe',
      tags: ['stability'],
      best: 'Overpronation support',
      desc: 'Guided stability without the bulk.',
      pop: 6,
    }),
    P({
      name: 'Ridge Trail GTX',
      cat: 'cat-lari-trail',
      price: 2_199_000,
      sizes: 'shoe',
      tags: ['waterproof', 'trail'],
      best: 'Wet mountain trails',
      desc: 'Waterproof trail shoe with deep lugs.',
      pop: 5,
    }),
    P({
      name: 'Ridge Trail Lite',
      cat: 'cat-lari-trail',
      price: 1_399_000,
      sizes: 'shoe',
      tags: ['trail'],
      best: 'Hard-packed trails and parks',
      desc: 'Light trail shoe for mixed terrain.',
      pop: 7,
    }),
    P({
      name: 'Summit Ultra',
      cat: 'cat-lari-trail',
      price: 2_699_000,
      sizes: 'shoe',
      tags: ['ultra', 'trail'],
      best: 'Ultra distance and vertical',
      desc: 'Protective ultra shoe with rock plate.',
      pop: 3,
      status: 'scheduled',
    }),
    P({
      name: 'AeroDry Tee',
      cat: 'cat-lari-apparel',
      price: 299_000,
      sizes: 'apparel',
      tags: ['quick dry'],
      best: 'Hot and humid runs',
      desc: 'Breathable tee that dries in minutes.',
      pop: 18,
    }),
    P({
      name: 'Split Shorts 5"',
      cat: 'cat-lari-apparel',
      price: 349_000,
      sizes: 'apparel',
      tags: ['race'],
      best: 'Race day and speed work',
      desc: 'Split-leg shorts with a phone pocket.',
      pop: 12,
    }),
    P({
      name: 'Long Tights Thermo',
      cat: 'cat-lari-apparel',
      price: 499_000,
      sizes: 'apparel',
      tags: ['thermal'],
      best: 'Early mornings and travel',
      desc: 'Light thermal tights.',
      pop: 4,
    }),
    P({
      name: 'Windbreaker Packable',
      cat: 'cat-lari-apparel',
      price: 649_000,
      sizes: 'apparel',
      tags: ['rain'],
      best: 'Rainy season runs',
      desc: 'Packs into its own pocket.',
      pop: 5,
    }),
    P({
      name: 'Club Singlet',
      cat: 'cat-lari-apparel',
      price: 249_000,
      sizes: 'apparel',
      tags: ['team'],
      best: 'Club runs and races',
      desc: 'Custom-ready singlet for running clubs.',
      pop: 8,
    }),
    P({
      name: 'Compression Socks',
      cat: 'cat-lari-acc',
      price: 149_000,
      sizes: 'apparel',
      tags: ['recovery'],
      best: 'Long runs and recovery',
      desc: 'Graduated compression socks.',
      pop: 20,
    }),
    P({
      name: 'Running Cap',
      cat: 'cat-lari-acc',
      price: 179_000,
      sizes: 'none',
      tags: ['sun'],
      best: 'Sunny race days',
      desc: 'Light cap with a sweat band.',
      pop: 10,
    }),
    P({
      name: 'Hydration Vest 5L',
      cat: 'cat-lari-acc',
      price: 899_000,
      sizes: 'apparel',
      tags: ['trail', 'hydration'],
      best: 'Trail and ultra',
      desc: 'Five litre vest with two soft flasks.',
      pop: 4,
    }),
    P({
      name: 'Race Belt',
      cat: 'cat-lari-acc',
      price: 129_000,
      sizes: 'none',
      tags: ['race'],
      best: 'Bib and gel carry',
      desc: 'Elastic belt with gel loops.',
      pop: 9,
    }),
    P({
      name: 'GPS Watch Pace 2',
      cat: 'cat-lari-acc',
      price: 3_499_000,
      sizes: 'none',
      tags: ['gps'],
      best: 'Training by pace and heart rate',
      desc: 'GPS watch with training load.',
      pop: 3,
    }),
    P({
      name: 'Energy Gel (12 pack)',
      cat: 'cat-lari-nutri',
      price: 216_000,
      sizes: 'none',
      tags: ['fuel'],
      best: 'Races over 15K',
      desc: 'Twelve isotonic gels, mixed flavours.',
      pop: 15,
    }),
    P({
      name: 'Electrolyte Tabs',
      cat: 'cat-lari-nutri',
      price: 99_000,
      sizes: 'none',
      tags: ['hydration'],
      best: 'Hot long runs',
      desc: 'Ten fizzing electrolyte tabs.',
      pop: 12,
    }),
    P({
      name: 'Recovery Shake',
      cat: 'cat-lari-nutri',
      price: 289_000,
      sizes: 'none',
      tags: ['recovery'],
      best: 'After long runs',
      desc: 'Whey and carbs, chocolate.',
      pop: 5,
    }),
    P({
      name: '10K Training Plan',
      cat: 'cat-lari-coach',
      price: 199_000,
      type: 'digital',
      sizes: 'none',
      tags: ['plan'],
      best: 'First 10K in eight weeks',
      desc: 'Eight-week plan with weekly check-ins.',
      pop: 6,
    }),
    P({
      name: 'Gait Analysis Session',
      cat: 'cat-lari-coach',
      price: 350_000,
      type: 'service',
      sizes: 'none',
      tags: ['fitting'],
      best: 'Choosing the right shoe',
      desc: 'Forty-five minute treadmill gait analysis.',
      pop: 4,
    }),
    P({
      name: 'Monthly Coaching',
      cat: 'cat-lari-coach',
      price: 450_000,
      type: 'subscription',
      sizes: 'none',
      tags: ['coach'],
      best: 'Structured training',
      desc: 'Personal coach, renews monthly.',
      pop: 3,
    }),
    P({
      name: 'Race Day Bundle',
      cat: 'cat-lari-acc',
      price: 499_000,
      compareAt: 594_000,
      type: 'bundle',
      sizes: 'none',
      tags: ['bundle', 'race'],
      best: 'Everything for your next race',
      desc: 'Belt, cap, gels and socks.',
      pop: 7,
    }),
    P({
      name: 'Velocity Pro 4 (pre-order)',
      cat: 'cat-lari-road',
      price: 2_799_000,
      type: 'preorder',
      sizes: 'shoe',
      tags: ['carbon plate', 'pre-order'],
      best: 'Next season racing',
      desc: 'Ships in November.',
      pop: 2,
    }),
    P({
      name: 'Corporate Team Kit',
      cat: 'cat-lari-apparel',
      price: 0,
      sizes: 'none',
      tags: ['b2b'],
      best: 'Company running teams of 20+',
      desc: 'Custom kits with logo printing.',
      assisted: true,
      pop: 0,
    }),
    P({
      name: 'Heritage Racer',
      cat: 'cat-lari-road',
      price: 1_099_000,
      sizes: 'shoe',
      tags: ['retro'],
      best: 'Lifestyle wear',
      desc: 'Retro racer, discontinued colourway.',
      status: 'archived',
      pop: 0,
    }),
    P({
      name: 'Night Reflective Vest',
      cat: 'cat-lari-acc',
      price: 199_000,
      sizes: 'apparel',
      tags: ['safety'],
      best: 'Running after dark',
      desc: '360 degree reflective vest.',
      status: 'draft',
      pop: 0,
    }),
  ],
  'ten-aruna': [
    P({
      name: 'Calm Barrier Serum',
      cat: 'cat-aruna-skin',
      price: 289_000,
      sizes: 'volume',
      tags: ['sensitive'],
      best: 'Sensitive, reactive skin',
      desc: 'Ceramide serum that calms redness.',
      pop: 18,
    }),
    P({
      name: 'Bright C Essence',
      cat: 'cat-aruna-skin',
      price: 259_000,
      sizes: 'volume',
      tags: ['brightening'],
      best: 'Dull skin and dark spots',
      desc: 'Vitamin C essence, 10 percent.',
      pop: 14,
    }),
    P({
      name: 'Gentle Gel Cleanser',
      cat: 'cat-aruna-skin',
      price: 129_000,
      sizes: 'volume',
      tags: ['daily'],
      best: 'Every skin type',
      desc: 'Low-pH gel cleanser.',
      pop: 20,
    }),
    P({
      name: 'Daily Sunscreen SPF50',
      cat: 'cat-aruna-skin',
      price: 149_000,
      sizes: 'volume',
      tags: ['spf'],
      best: 'Everyday protection',
      desc: 'Light, no white cast.',
      pop: 22,
    }),
    P({
      name: 'Night Repair Cream',
      cat: 'cat-aruna-skin',
      price: 329_000,
      sizes: 'volume',
      tags: ['anti-aging'],
      best: 'Mature skin',
      desc: 'Retinal night cream.',
      pop: 9,
    }),
    P({
      name: 'Hydra Toner',
      cat: 'cat-aruna-skin',
      price: 159_000,
      sizes: 'volume',
      tags: ['hydrating'],
      best: 'Dehydrated skin',
      desc: 'Five hyaluronic acids.',
      pop: 12,
    }),
    P({
      name: 'Clay Detox Mask',
      cat: 'cat-aruna-skin',
      price: 179_000,
      sizes: 'none',
      tags: ['oily'],
      best: 'Oily, congested skin',
      desc: 'Kaolin and bentonite mask.',
      pop: 7,
    }),
    P({
      name: 'Velvet Lip Matte',
      cat: 'cat-aruna-makeup',
      price: 119_000,
      sizes: 'shade',
      tags: ['lip'],
      best: 'All-day colour',
      desc: 'Matte lip that does not dry.',
      pop: 16,
    }),
    P({
      name: 'Skin Tint Cushion',
      cat: 'cat-aruna-makeup',
      price: 219_000,
      sizes: 'shade',
      tags: ['base'],
      best: 'Natural coverage',
      desc: 'Dewy cushion with SPF35.',
      pop: 11,
    }),
    P({
      name: 'Brow Pencil',
      cat: 'cat-aruna-makeup',
      price: 89_000,
      sizes: 'shade',
      tags: ['brow'],
      best: 'Defined natural brows',
      desc: 'Slim pencil with a spoolie.',
      pop: 9,
    }),
    P({
      name: 'Lash Lift Mascara',
      cat: 'cat-aruna-makeup',
      price: 139_000,
      sizes: 'none',
      tags: ['eye'],
      best: 'Straight lashes',
      desc: 'Curl-holding mascara.',
      pop: 8,
    }),
    P({
      name: 'Blush Stick',
      cat: 'cat-aruna-makeup',
      price: 129_000,
      sizes: 'shade',
      tags: ['cheek'],
      best: 'Quick colour on the go',
      desc: 'Creamy blush stick.',
      pop: 6,
    }),
    P({
      name: 'Scalp Care Shampoo',
      cat: 'cat-aruna-hair',
      price: 149_000,
      sizes: 'volume',
      tags: ['scalp'],
      best: 'Oily scalp',
      desc: 'Salicylic scalp shampoo.',
      pop: 8,
    }),
    P({
      name: 'Silk Hair Oil',
      cat: 'cat-aruna-hair',
      price: 169_000,
      sizes: 'volume',
      tags: ['frizz'],
      best: 'Frizzy hair',
      desc: 'Argan and camellia oil.',
      pop: 7,
    }),
    P({
      name: 'Melati Eau de Parfum',
      cat: 'cat-aruna-frag',
      price: 459_000,
      sizes: 'volume',
      tags: ['floral'],
      best: 'Evening and gifts',
      desc: 'Jasmine, tuberose and musk.',
      pop: 5,
    }),
    P({
      name: 'Kopi Senja EDP',
      cat: 'cat-aruna-frag',
      price: 459_000,
      sizes: 'volume',
      tags: ['gourmand'],
      best: 'Everyday signature',
      desc: 'Coffee, vanilla and cedar.',
      pop: 4,
    }),
    P({
      name: 'Sensitive Starter Set',
      cat: 'cat-aruna-sets',
      price: 499_000,
      compareAt: 576_000,
      type: 'bundle',
      sizes: 'none',
      tags: ['bundle', 'sensitive'],
      best: 'First routine for sensitive skin',
      desc: 'Cleanser, serum and sunscreen.',
      pop: 10,
    }),
    P({
      name: 'Bridal Glow Kit',
      cat: 'cat-aruna-sets',
      price: 899_000,
      type: 'bundle',
      sizes: 'none',
      tags: ['bundle', 'bridal'],
      best: 'Wedding prep in four weeks',
      desc: 'Four-week glow routine.',
      pop: 3,
    }),
    P({
      name: 'Skin Consultation',
      cat: 'cat-aruna-sets',
      price: 150_000,
      type: 'service',
      sizes: 'none',
      tags: ['consult'],
      best: 'Building a routine',
      desc: 'Thirty-minute video consultation.',
      pop: 3,
    }),
    P({
      name: 'Aruna Box Subscription',
      cat: 'cat-aruna-sets',
      price: 299_000,
      type: 'subscription',
      sizes: 'none',
      tags: ['subscription'],
      best: 'Monthly favourites',
      desc: 'Four minis every month.',
      pop: 4,
    }),
    P({
      name: 'Peptide Eye Cream',
      cat: 'cat-aruna-skin',
      price: 269_000,
      sizes: 'volume',
      tags: ['eye'],
      best: 'Fine lines around the eyes',
      desc: 'Launching soon.',
      status: 'scheduled',
      pop: 0,
    }),
  ],
  'ten-teknika': [
    P({
      name: 'VMC-850 Vertical Machining Center',
      cat: 'cat-tek-cnc',
      price: 0,
      sizes: 'spec',
      tags: ['cnc', 'milling'],
      best: 'Mould and die shops',
      desc: 'Travel 850 × 500 × 550 mm, 10,000 rpm.',
      assisted: true,
      pop: 0,
    }),
    P({
      name: 'TL-300 CNC Lathe',
      cat: 'cat-tek-cnc',
      price: 0,
      sizes: 'spec',
      tags: ['cnc', 'turning'],
      best: 'Shaft and flange production',
      desc: 'Max turning diameter 300 mm.',
      assisted: true,
      pop: 0,
    }),
    P({
      name: 'HMC-500 Horizontal Center',
      cat: 'cat-tek-cnc',
      price: 0,
      sizes: 'spec',
      tags: ['cnc'],
      best: 'High-mix automotive parts',
      desc: 'Twin pallet changer.',
      assisted: true,
      pop: 0,
    }),
    P({
      name: 'Screw Compressor 37 kW',
      cat: 'cat-tek-air',
      price: 186_000_000,
      sizes: 'none',
      tags: ['compressor'],
      best: 'Plants with 6 m³/min demand',
      desc: 'Oil-injected, variable speed.',
      pop: 2,
    }),
    P({
      name: 'Refrigerated Air Dryer',
      cat: 'cat-tek-air',
      price: 42_500_000,
      sizes: 'none',
      tags: ['dryer'],
      best: 'Pairs with 22 to 45 kW compressors',
      desc: 'Dew point 3 °C.',
      pop: 2,
    }),
    P({
      name: 'Air Filter Element Set',
      cat: 'cat-tek-parts',
      price: 2_350_000,
      sizes: 'none',
      tags: ['filter'],
      best: 'Quarterly compressor service',
      desc: 'Intake, oil and separator elements.',
      pop: 9,
    }),
    P({
      name: 'Spindle Bearing Kit',
      cat: 'cat-tek-parts',
      price: 18_900_000,
      sizes: 'none',
      tags: ['bearing'],
      best: 'VMC spindle rebuilds',
      desc: 'Matched angular contact set.',
      pop: 3,
    }),
    P({
      name: 'Way Lube Oil 20L',
      cat: 'cat-tek-parts',
      price: 1_450_000,
      sizes: 'none',
      tags: ['oil'],
      best: 'Slideway lubrication',
      desc: 'ISO VG 68.',
      pop: 12,
    }),
    P({
      name: 'Coolant Concentrate 20L',
      cat: 'cat-tek-parts',
      price: 2_100_000,
      sizes: 'none',
      tags: ['coolant'],
      best: 'Steel and aluminium machining',
      desc: 'Semi-synthetic, 5 percent mix.',
      pop: 10,
    }),
    P({
      name: 'Tool Holder BT40',
      cat: 'cat-tek-parts',
      price: 1_250_000,
      sizes: 'none',
      tags: ['tooling'],
      best: 'VMC tool changers',
      desc: 'ER32 collet chuck.',
      pop: 8,
    }),
    P({
      name: 'Preventive Service Contract',
      cat: 'cat-tek-service',
      price: 36_000_000,
      type: 'subscription',
      sizes: 'none',
      tags: ['service'],
      best: 'One machine, quarterly visits',
      desc: 'Four visits a year, parts discount.',
      pop: 2,
    }),
    P({
      name: 'On-site Commissioning',
      cat: 'cat-tek-service',
      price: 12_500_000,
      type: 'service',
      sizes: 'none',
      tags: ['service'],
      best: 'New machine installation',
      desc: 'Levelling, test cut and training.',
      pop: 2,
    }),
  ],
}

const OPTION_NAME: Record<NonNullable<ProductSeed['sizes']>, string | null> = {
  shoe: 'Size',
  apparel: 'Size',
  shade: 'Shade',
  volume: 'Volume',
  none: null,
  spec: null,
}

/** Colourways for products sold in more than one colour; the first keeps the original variant ids. */
const COLOURS: Record<string, string[]> = {
  'Velocity Pro 3': ['Volt', 'Black'],
  'Velocity Trainer': ['White', 'Navy', 'Coral'],
  'Swift 5K': ['Grey', 'Pink'],
  'AeroDry Tee': ['Black', 'White', 'Red'],
  'Split Shorts 5"': ['Black', 'Navy'],
  'Ridge Trail Lite': ['Olive', 'Black'],
}

const SIZE_SETS: Record<NonNullable<ProductSeed['sizes']>, string[]> = {
  shoe: ['39', '40', '41', '42', '43', '44'],
  apparel: ['S', 'M', 'L', 'XL'],
  shade: ['01 Nude', '02 Rose', '03 Brick'],
  volume: ['30 ml', '50 ml'],
  none: ['Standard'],
  spec: ['Standard'],
}

export const categories: Category[] = Object.entries(CATEGORIES).flatMap(([tenantId, list]) =>
  list.map((c) => ({ ...c, tenantId })),
)

export const products: Product[] = []
for (const [tenantId, seeds] of Object.entries(SEEDS)) {
  const prefix = tenantId === 'ten-lari' ? 'LR' : tenantId === 'ten-aruna' ? 'AR' : 'TK'
  seeds.forEach((s, i) => {
    const code = `${prefix}-${String(101 + i)}`
    const sizes = SIZE_SETS[s.sizes ?? 'none']
    const sizeOption = OPTION_NAME[s.sizes ?? 'none']
    const colours = COLOURS[s.name] ?? []
    const options = [
      ...(sizeOption ? [{ name: sizeOption, values: sizes }] : []),
      ...(colours.length ? [{ name: 'Colour', values: colours }] : []),
    ]
    const variants: Variant[] = (colours.length ? colours : [null]).flatMap((colour, c) =>
      sizes.map((size, j) => {
        const optionValues: Record<string, string> = {
          ...(sizeOption ? { [sizeOption]: size } : {}),
          ...(colour ? { Colour: colour } : {}),
        }
        return {
          id: c === 0 ? `var-${code.toLowerCase()}-${j + 1}` : `var-${code.toLowerCase()}-c${c + 1}-${j + 1}`,
          sku: [
            code,
            sizes.length > 1 ? size.split(' ')[0] : null,
            colour ? colour.slice(0, 3).toUpperCase() : null,
          ]
            .filter(Boolean)
            .join('-'),
          name: Object.values(optionValues).join(' / ') || 'Standard',
          optionValues,
          price: s.sizes === 'volume' && j === 1 ? Math.round((s.price * 1.5) / 1000) * 1000 : s.price,
          barcode: `899${String(1000000000 + i * 97 + j * 13 + c * 7).slice(0, 10)}`,
        }
      }),
    )
    products.push({
      id: `prd-${code.toLowerCase()}`,
      tenantId,
      code,
      name: s.name,
      categoryId: s.cat,
      type: s.type ?? 'physical',
      status: s.status ?? 'active',
      price: s.price,
      compareAt: s.compareAt ?? null,
      memberPrice: s.price > 500_000 && !s.assisted ? Math.round((s.price * 0.95) / 1000) * 1000 : null,
      cost: Math.round((s.price * rng.float(0.42, 0.6)) / 1000) * 1000,
      tags: s.tags ?? [],
      options,
      attributes: {},
      description: s.desc,
      bestFor: s.best,
      variants,
      rating: s.pop ? rng.round(rng.float(4.1, 4.9), 1) : 0,
      reviewCount: s.pop ? Math.round(s.pop * rng.int(4, 12)) : 0,
      views30d: s.assisted ? rng.int(300, 900) : Math.round(((s.pop ?? 0) + 1) * rng.int(110, 190)),
      assisted: !!s.assisted,
      createdAt: isoDaysAgo(rng.int(120, 230)),
      publishAt: s.status === 'scheduled' ? isoDaysAgo(-9, 9) : null,
    })
  })
}

/** How often a product appears in generated orders. */
export const popularity = new Map<string, number>()
for (const [tenantId, seeds] of Object.entries(SEEDS)) {
  const list = products.filter((p) => p.tenantId === tenantId)
  seeds.forEach((s, i) => popularity.set(list[i]!.id, s.status === 'active' || !s.status ? (s.pop ?? 0) : 0))
}

type CollectionSeed = Pick<Collection, 'id' | 'tenantId' | 'name' | 'description'> & Partial<Collection>
const col = (c: CollectionSeed): Collection => ({
  slug: c.name.toLowerCase().replace(/[^a-z0-9]+/g, '-'),
  mode: 'manual',
  productIds: [],
  ruleCategoryIds: [],
  ruleTags: [],
  featured: false,
  ...c,
})

export const collections: Collection[] = [
  col({
    id: 'col-lari-race',
    tenantId: 'ten-lari',
    name: 'Race day',
    description: 'Everything for the start line.',
    featured: true,
    productIds: ['prd-lr-101', 'prd-lr-111', 'prd-lr-118', 'prd-lr-120', 'prd-lr-126'],
  }),
  col({
    id: 'col-lari-10k',
    tenantId: 'ten-lari',
    name: 'Your first 10K',
    description: 'Forgiving shoes and a plan.',
    featured: true,
    productIds: ['prd-lr-103', 'prd-lr-102', 'prd-lr-110', 'prd-lr-123', 'prd-lr-115'],
  }),
  col({
    id: 'col-lari-trail',
    tenantId: 'ten-lari',
    name: 'Trail season',
    description: 'Grip, protection and water.',
    mode: 'smart',
    ruleCategoryIds: ['cat-lari-trail'],
    ruleTags: ['trail'],
  }),
  col({
    id: 'col-lari-carbon',
    tenantId: 'ten-lari',
    name: 'Carbon plate racers',
    description: 'Every shoe with a carbon plate.',
    mode: 'smart',
    ruleTags: ['carbon plate'],
    featured: true,
  }),
  col({
    id: 'col-aruna-sensitive',
    tenantId: 'ten-aruna',
    name: 'Sensitive skin',
    description: 'Calm, fragrance-free picks.',
    featured: true,
    productIds: ['prd-ar-101', 'prd-ar-103', 'prd-ar-104', 'prd-ar-117'],
  }),
  col({
    id: 'col-aruna-bridal',
    tenantId: 'ten-aruna',
    name: 'Bridal glow',
    description: 'Four weeks to the big day.',
    productIds: ['prd-ar-118', 'prd-ar-102', 'prd-ar-109', 'prd-ar-108'],
  }),
  col({
    id: 'col-aruna-makeup',
    tenantId: 'ten-aruna',
    name: 'Everyday makeup',
    description: 'Lips, brows and base for every day.',
    mode: 'smart',
    ruleCategoryIds: ['cat-aruna-makeup'],
    featured: true,
  }),
  col({
    id: 'col-tek-maint',
    tenantId: 'ten-teknika',
    name: 'Maintenance consumables',
    description: 'Reorder in one click.',
    featured: true,
    productIds: ['prd-tk-106', 'prd-tk-108', 'prd-tk-109', 'prd-tk-110'],
  }),
]
