import type {
  BrandConfig,
  Seller,
  Template,
  Tenant,
  User,
  Warehouse,
} from '../../packages/types/src/index.ts'
import { DAY, toIso, toMs } from '../../packages/fixtures/src/dates.ts'
import { FIXTURE_NOW } from '../../packages/fixtures/src/clock.ts'

export const NOW = toMs(FIXTURE_NOW)
export const daysAgo = (d: number, hour = 10, minute = 0) => {
  const base = NOW - d * DAY
  const date = new Date(base + 7 * 3_600_000)
  return Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate(), hour, minute) - 7 * 3_600_000
}
export const isoDaysAgo = (d: number, hour = 10, minute = 0) => toIso(daysAgo(d, hour, minute))

const allLocked = (locked: boolean): BrandConfig['locks'] => ({
  logo: true,
  primary_color: true,
  button_style: true,
  hero_image: !locked,
  headline: false,
  featured_product: false,
  layout: false,
})

export const tenants: Tenant[] = [
  {
    id: 'ten-lari',
    code: 'LARI',
    name: 'Lari Running Co.',
    industry: 'sport',
    plan: 'growth',
    subdomain: 'lari',
    domain: 'www.lari.co.id',
    domainVerified: true,
    createdAt: isoDaysAgo(240),
    brand: {
      colors: {
        primary: '#d62839',
        secondary: '#111111',
        accent: '#ffb703',
        background: '#ffffff',
        text: '#111111',
      },
      fonts: { heading: 'DM Sans', body: 'DM Sans' },
      theme: 'theme1',
      radius: 'soft',
      buttonStyle: 'pill',
      personality: 'bold',
      tone: 'energetic',
      tagline: 'Gear for every kilometre.',
      locks: allLocked(false),
    },
    loyalty: {
      pointsPer10k: 1,
      thresholds: { silver: 1_500_000, gold: 5_000_000, platinum: 10_000_000 },
      freeShippingMin: 750_000,
    },
    onboarding: [
      'business',
      'brand',
      'template',
      'commerce',
      'payment',
      'shipping',
      'products',
      'users',
      'preview',
      'publish',
    ],
  },
  {
    id: 'ten-aruna',
    code: 'ARUNA',
    name: 'Aruna Beauty',
    industry: 'beauty',
    plan: 'growth',
    subdomain: 'aruna',
    domain: 'aruna.id',
    domainVerified: true,
    createdAt: isoDaysAgo(200),
    brand: {
      colors: {
        primary: '#6f4352',
        secondary: '#efe4df',
        accent: '#b99668',
        background: '#fcf8f4',
        text: '#2b2326',
      },
      fonts: { heading: 'DM Sans', body: 'DM Sans' },
      theme: 'theme2',
      radius: 'round',
      buttonStyle: 'solid',
      personality: 'premium',
      tone: 'friendly',
      tagline: 'Skin that tells your story.',
      locks: allLocked(true),
    },
    loyalty: {
      pointsPer10k: 2,
      thresholds: { silver: 1_500_000, gold: 4_000_000, platinum: 10_000_000 },
      freeShippingMin: 300_000,
    },
    onboarding: [
      'business',
      'brand',
      'template',
      'commerce',
      'payment',
      'shipping',
      'products',
      'users',
      'preview',
      'publish',
    ],
  },
  {
    id: 'ten-teknika',
    code: 'TEKNIKA',
    name: 'Teknika Industrial',
    industry: 'industrial',
    plan: 'enterprise',
    subdomain: 'teknika',
    domain: null,
    domainVerified: false,
    createdAt: isoDaysAgo(60),
    brand: {
      colors: {
        primary: '#1e3a52',
        secondary: '#2a2f33',
        accent: '#b98a4b',
        background: '#f7f6f3',
        text: '#181b1e',
      },
      fonts: { heading: 'DM Sans', body: 'DM Sans' },
      theme: 'theme2',
      radius: 'sharp',
      buttonStyle: 'solid',
      personality: 'corporate',
      tone: 'professional',
      tagline: 'Machines that keep your line running.',
      locks: allLocked(true),
    },
    loyalty: {
      pointsPer10k: 0,
      thresholds: { silver: 50_000_000, gold: 200_000_000, platinum: 500_000_000 },
      freeShippingMin: 5_000_000,
    },
    onboarding: ['business', 'brand', 'template', 'commerce', 'payment', 'shipping', 'products'],
  },
]

export const users: User[] = [
  {
    id: 'usr-dewi',
    name: 'Dewi Lestari',
    email: 'dewi@commerceos.id',
    title: 'Platform operations',
    role: 'platform_admin',
    tenantIds: ['ten-lari', 'ten-aruna', 'ten-teknika'],
    color: '#101112',
  },
  {
    id: 'usr-andi',
    name: 'Andi Pratama',
    email: 'andi@lari.co.id',
    title: 'Head of e-commerce',
    role: 'tenant_admin',
    tenantIds: ['ten-lari', 'ten-aruna'],
    color: '#4c5a78',
  },
  {
    id: 'usr-hendra',
    name: 'Hendra Wijaya',
    email: 'hendra@teknika.co.id',
    title: 'Commercial director',
    role: 'tenant_admin',
    tenantIds: ['ten-teknika'],
    color: '#3f7a7b',
  },
  {
    id: 'usr-maya',
    name: 'Maya Putri',
    email: 'maya@lari.co.id',
    title: 'CRM & campaign lead',
    role: 'marketing',
    tenantIds: ['ten-lari', 'ten-aruna'],
    color: '#6a5a8c',
  },
  {
    id: 'usr-budi',
    name: 'Budi Santoso',
    email: 'budi@lari.co.id',
    title: 'Fulfilment lead',
    role: 'operations',
    tenantIds: ['ten-lari', 'ten-aruna', 'ten-teknika'],
    color: '#557a5c',
  },
  {
    id: 'usr-sari',
    name: 'Sari Wulandari',
    email: 'sari@lari.co.id',
    title: 'Customer care',
    role: 'service',
    tenantIds: ['ten-lari', 'ten-aruna'],
    color: '#8a5a6e',
  },
  {
    id: 'usr-fahmi',
    name: 'Fahmi Rahman',
    email: 'fahmi@lari.co.id',
    title: 'Store sales, Senayan',
    role: 'sales',
    tenantIds: ['ten-lari'],
    color: '#4f6f94',
  },
  {
    id: 'usr-sherlyn',
    name: 'Sherlyn Tan',
    email: 'sherlyn@lari.co.id',
    title: 'Brand ambassador',
    role: 'sales',
    tenantIds: ['ten-lari', 'ten-aruna'],
    color: '#7a6b3f',
  },
  {
    id: 'usr-rizky',
    name: 'Rizky Hidayat',
    email: 'rizky@teknika.co.id',
    title: 'Account executive',
    role: 'sales',
    tenantIds: ['ten-teknika', 'ten-lari'],
    color: '#5c5c7a',
  },
]

export const warehouses: Warehouse[] = [
  { id: 'wh-lari-ckr', tenantId: 'ten-lari', code: 'CKR', name: 'Cikarang DC', city: 'Bekasi' },
  { id: 'wh-lari-sby', tenantId: 'ten-lari', code: 'SBY', name: 'Surabaya hub', city: 'Surabaya' },
  { id: 'wh-aruna-jkt', tenantId: 'ten-aruna', code: 'JKT', name: 'Jakarta DC', city: 'Jakarta' },
  { id: 'wh-aruna-bdg', tenantId: 'ten-aruna', code: 'BDG', name: 'Bandung hub', city: 'Bandung' },
  { id: 'wh-tek-ckr', tenantId: 'ten-teknika', code: 'CKR', name: 'Cikarang yard', city: 'Bekasi' },
]

const sec = (
  kind: Template['sections'][number]['kind'],
  rule: Template['sections'][number]['rule'] = 'optional',
) => ({ kind, rule })

export const templates: Template[] = [
  {
    id: 'tpl-minimal',
    tenantId: null,
    name: 'Minimal Commerce',
    scope: 'store',
    description: 'Quiet layout that lets product photography lead.',
    bestFor: 'Fashion, lifestyle, beauty',
    sections: [
      sec('hero', 'required'),
      sec('category'),
      sec('featured_product', 'required'),
      sec('collection'),
      sec('brand_story'),
      sec('testimonials'),
      sec('footer', 'locked'),
    ],
  },
  {
    id: 'tpl-conversion',
    tenantId: null,
    name: 'Conversion Focus',
    scope: 'campaign',
    description: 'Offer first, countdown and one strong call to action.',
    bestFor: 'Promotion, FMCG, flash sale',
    sections: [
      sec('hero', 'required'),
      sec('countdown'),
      sec('promotion', 'required'),
      sec('featured_product', 'required'),
      sec('testimonials'),
      sec('faq'),
      sec('cta', 'required'),
      sec('footer', 'locked'),
    ],
  },
  {
    id: 'tpl-editorial',
    tenantId: null,
    name: 'Premium Editorial',
    scope: 'store',
    description: 'Magazine pacing with large imagery and brand story.',
    bestFor: 'Luxury, jewelry, automotive',
    sections: [
      sec('hero', 'required'),
      sec('brand_story', 'required'),
      sec('featured_product'),
      sec('collection'),
      sec('testimonials'),
      sec('footer', 'locked'),
    ],
  },
  {
    id: 'tpl-catalog',
    tenantId: null,
    name: 'Catalog Heavy',
    scope: 'store',
    description: 'Dense category grid, comparison and Talk to sales.',
    bestFor: 'Electronics, B2B, industrial',
    sections: [
      sec('hero', 'required'),
      sec('category', 'required'),
      sec('collection'),
      sec('comparison'),
      sec('faq'),
      sec('cta'),
      sec('footer', 'locked'),
    ],
  },
  {
    id: 'tpl-launch',
    tenantId: null,
    name: 'Editorial Launch',
    scope: 'campaign',
    description: 'Story-led product launch with countdown and early access.',
    bestFor: 'Product launch, limited drop',
    sections: [
      sec('hero', 'required'),
      sec('brand_story'),
      sec('countdown'),
      sec('featured_product', 'required'),
      sec('comparison'),
      sec('cta', 'required'),
      sec('footer', 'locked'),
    ],
  },
  {
    id: 'tpl-sales-pro',
    tenantId: null,
    name: 'Sales Professional',
    scope: 'personal',
    description: 'Profile, credentials and a direct WhatsApp line.',
    bestFor: 'In-house sales, B2B account executives',
    sections: [
      sec('hero', 'required'),
      sec('featured_product', 'required'),
      sec('testimonials'),
      sec('cta', 'required'),
      sec('footer', 'locked'),
    ],
  },
  {
    id: 'tpl-personal-store',
    tenantId: null,
    name: 'Personal Store',
    scope: 'personal',
    description: 'A small shop front with picks, collections and a promo.',
    bestFor: 'Resellers, affiliates, ambassadors',
    sections: [
      sec('hero', 'required'),
      sec('promotion'),
      sec('featured_product', 'required'),
      sec('collection'),
      sec('testimonials'),
      sec('footer', 'locked'),
    ],
  },
  {
    id: 'tpl-specialist',
    tenantId: null,
    name: 'Product Specialist',
    scope: 'personal',
    description: 'Comparison and expert advice for considered purchases.',
    bestFor: 'Running coaches, beauty advisors',
    sections: [
      sec('hero', 'required'),
      sec('comparison'),
      sec('featured_product', 'required'),
      sec('faq'),
      sec('cta', 'required'),
      sec('footer', 'locked'),
    ],
  },
  {
    id: 'tpl-luxury',
    tenantId: null,
    name: 'Luxury Editorial',
    scope: 'personal',
    description: 'Large portrait, story and a short curated edit.',
    bestFor: 'Premium advisors and private clients',
    sections: [
      sec('hero', 'required'),
      sec('brand_story'),
      sec('featured_product', 'required'),
      sec('cta', 'required'),
      sec('footer', 'locked'),
    ],
  },
]

const PERSONAL = ['tpl-sales-pro', 'tpl-personal-store', 'tpl-specialist', 'tpl-luxury']

type SellerSeed = Omit<Seller, 'joinedAt' | 'featuredProductIds' | 'allowedTemplateIds' | 'templateId'> & {
  joinedDaysAgo: number
  templateId?: string
  allowed?: string[]
}

const sellerSeeds: SellerSeed[] = [
  {
    id: 'sel-fahmi',
    tenantId: 'ten-lari',
    userId: 'usr-fahmi',
    code: 'S-001',
    name: 'Fahmi Rahman',
    kind: 'sales',
    slug: 'fahmi',
    status: 'active',
    city: 'Jakarta',
    bio: 'Marathoner (3:28 PB) helping runners pick the right shoe for their pace.',
    headline: 'Find your race-day shoe.',
    whatsapp: '+62 812 1000 2001',
    instagram: '@fahmiruns',
    commissionRate: 0.05,
    color: '#4f6f94',
    joinedDaysAgo: 220,
    templateId: 'tpl-sales-pro',
    allowed: ['tpl-sales-pro', 'tpl-personal-store', 'tpl-specialist'],
  },
  {
    id: 'sel-sherlyn',
    tenantId: 'ten-lari',
    userId: 'usr-sherlyn',
    code: 'S-002',
    name: 'Sherlyn Tan',
    kind: 'sales',
    slug: 'sherlyn',
    status: 'active',
    city: 'Jakarta',
    bio: 'Trail runner and community lead of Sunday Long Run Club.',
    headline: 'Trail picks from the club.',
    whatsapp: '+62 812 1000 2002',
    instagram: '@sherlyn.trail',
    commissionRate: 0.05,
    color: '#7a6b3f',
    joinedDaysAgo: 210,
    templateId: 'tpl-personal-store',
    allowed: ['tpl-sales-pro', 'tpl-personal-store', 'tpl-specialist'],
  },
  {
    id: 'sel-rizky-lari',
    tenantId: 'ten-lari',
    userId: 'usr-rizky',
    code: 'S-003',
    name: 'Rizky Hidayat',
    kind: 'sales',
    slug: 'rizky',
    status: 'active',
    city: 'Bandung',
    bio: 'Corporate team kits and race-event bundles.',
    headline: 'Kits for your whole running team.',
    whatsapp: '+62 812 1000 2003',
    instagram: null,
    commissionRate: 0.04,
    color: '#5c5c7a',
    joinedDaysAgo: 150,
    templateId: 'tpl-sales-pro',
    allowed: ['tpl-sales-pro', 'tpl-personal-store'],
  },
  {
    id: 'sel-nadia',
    tenantId: 'ten-lari',
    userId: null,
    code: 'A-011',
    name: 'Nadia Kusuma',
    kind: 'affiliate',
    slug: 'nadia',
    status: 'active',
    city: 'Surabaya',
    bio: 'Running content creator, 120k followers.',
    headline: 'My everyday running kit.',
    whatsapp: '+62 812 1000 2011',
    instagram: '@nadiaberlari',
    commissionRate: 0.08,
    color: '#8a4a5e',
    joinedDaysAgo: 120,
  },
  {
    id: 'sel-bayu',
    tenantId: 'ten-lari',
    userId: null,
    code: 'R-021',
    name: 'Bayu Saputra',
    kind: 'reseller',
    slug: 'bayu',
    status: 'active',
    city: 'Yogyakarta',
    bio: 'Running store reseller in Jogja.',
    headline: 'Lari gear, now in Jogja.',
    whatsapp: '+62 812 1000 2021',
    instagram: '@bayurun.jogja',
    commissionRate: 0.12,
    color: '#4f6f5a',
    joinedDaysAgo: 180,
  },
  {
    id: 'sel-citra',
    tenantId: 'ten-lari',
    userId: null,
    code: 'A-012',
    name: 'Citra Maharani',
    kind: 'agent',
    slug: 'citra',
    status: 'active',
    city: 'Medan',
    bio: 'Coach for beginner 5K and 10K runners.',
    headline: 'Start running the right way.',
    whatsapp: '+62 812 1000 2012',
    instagram: '@coachcitra',
    commissionRate: 0.07,
    color: '#8f6a3e',
    joinedDaysAgo: 90,
    templateId: 'tpl-specialist',
  },
  {
    id: 'sel-dimas',
    tenantId: 'ten-lari',
    userId: null,
    code: 'A-013',
    name: 'Dimas Aditya',
    kind: 'affiliate',
    slug: 'dimas',
    status: 'invited',
    city: 'Semarang',
    bio: '',
    headline: '',
    whatsapp: '+62 812 1000 2013',
    instagram: null,
    commissionRate: 0.08,
    color: '#3f6f78',
    joinedDaysAgo: 4,
  },
  {
    id: 'sel-eka',
    tenantId: 'ten-lari',
    userId: null,
    code: 'R-022',
    name: 'Eka Prasetyo',
    kind: 'reseller',
    slug: 'eka',
    status: 'suspended',
    city: 'Makassar',
    bio: 'Reseller, paused after price-policy breach.',
    headline: 'Lari gear in Makassar.',
    whatsapp: '+62 812 1000 2022',
    instagram: null,
    commissionRate: 0.1,
    color: '#5e5478',
    joinedDaysAgo: 160,
  },
  {
    id: 'sel-sherlyn-aruna',
    tenantId: 'ten-aruna',
    userId: 'usr-sherlyn',
    code: 'B-001',
    name: 'Sherlyn Tan',
    kind: 'sales',
    slug: 'sherlyn',
    status: 'active',
    city: 'Jakarta',
    bio: 'Beauty advisor for sensitive skin routines.',
    headline: 'Routines for calm, clear skin.',
    whatsapp: '+62 812 1000 3001',
    instagram: '@sherlyn.skin',
    commissionRate: 0.06,
    color: '#7a6b3f',
    joinedDaysAgo: 190,
    templateId: 'tpl-luxury',
    allowed: PERSONAL,
  },
  {
    id: 'sel-intan',
    tenantId: 'ten-aruna',
    userId: null,
    code: 'B-002',
    name: 'Intan Permata',
    kind: 'agent',
    slug: 'intan',
    status: 'active',
    city: 'Bandung',
    bio: 'Make-up artist and bridal specialist.',
    headline: 'Wedding-day glow.',
    whatsapp: '+62 812 1000 3002',
    instagram: '@intanmua',
    commissionRate: 0.08,
    color: '#8a4a5e',
    joinedDaysAgo: 150,
    templateId: 'tpl-specialist',
    allowed: PERSONAL,
  },
  {
    id: 'sel-putri',
    tenantId: 'ten-aruna',
    userId: null,
    code: 'B-003',
    name: 'Putri Ayu',
    kind: 'affiliate',
    slug: 'putri',
    status: 'active',
    city: 'Surabaya',
    bio: 'Skincare reviewer.',
    headline: 'What I actually use.',
    whatsapp: '+62 812 1000 3003',
    instagram: '@putriayu',
    commissionRate: 0.1,
    color: '#5e5478',
    joinedDaysAgo: 100,
  },
  {
    id: 'sel-lina',
    tenantId: 'ten-aruna',
    userId: null,
    code: 'B-004',
    name: 'Lina Marlina',
    kind: 'reseller',
    slug: 'lina',
    status: 'active',
    city: 'Makassar',
    bio: 'Beauty reseller in Makassar.',
    headline: 'Aruna, delivered in Makassar.',
    whatsapp: '+62 812 1000 3004',
    instagram: null,
    commissionRate: 0.12,
    color: '#4f6f5a',
    joinedDaysAgo: 120,
  },
  {
    id: 'sel-rizky',
    tenantId: 'ten-teknika',
    userId: 'usr-rizky',
    code: 'AE-01',
    name: 'Rizky Hidayat',
    kind: 'sales',
    slug: 'rizky',
    status: 'active',
    city: 'Bekasi',
    bio: 'Account executive for CNC and compressed-air systems.',
    headline: 'Machines sized to your line.',
    whatsapp: '+62 812 1000 4001',
    instagram: null,
    commissionRate: 0.015,
    color: '#5c5c7a',
    joinedDaysAgo: 58,
    templateId: 'tpl-sales-pro',
    allowed: ['tpl-sales-pro', 'tpl-specialist'],
  },
  {
    id: 'sel-agus',
    tenantId: 'ten-teknika',
    userId: null,
    code: 'AE-02',
    name: 'Agus Setiawan',
    kind: 'sales',
    slug: 'agus',
    status: 'active',
    city: 'Surabaya',
    bio: 'Account executive for East Java plants.',
    headline: 'Industrial supply for East Java.',
    whatsapp: '+62 812 1000 4002',
    instagram: null,
    commissionRate: 0.015,
    color: '#3f5a7a',
    joinedDaysAgo: 55,
    templateId: 'tpl-sales-pro',
    allowed: ['tpl-sales-pro', 'tpl-specialist'],
  },
  {
    id: 'sel-wulan',
    tenantId: 'ten-teknika',
    userId: null,
    code: 'DL-01',
    name: 'Wulan Sari',
    kind: 'agent',
    slug: 'wulan',
    status: 'active',
    city: 'Batam',
    bio: 'Distributor agent for Batam industrial estates.',
    headline: 'Teknika in Batam.',
    whatsapp: '+62 812 1000 4003',
    instagram: null,
    commissionRate: 0.03,
    color: '#3f6f78',
    joinedDaysAgo: 40,
    templateId: 'tpl-specialist',
    allowed: ['tpl-sales-pro', 'tpl-specialist'],
  },
]

export function buildSellers(featured: (tenantId: string, index: number) => string[]): Seller[] {
  return sellerSeeds.map(({ joinedDaysAgo, templateId, allowed, ...s }, i) => ({
    ...s,
    templateId: templateId ?? 'tpl-personal-store',
    allowedTemplateIds: allowed ?? ['tpl-personal-store', 'tpl-sales-pro'],
    featuredProductIds: featured(s.tenantId, i),
    joinedAt: isoDaysAgo(joinedDaysAgo),
  }))
}

export const FIRST_NAMES = [
  'Ahmad',
  'Ayu',
  'Bagus',
  'Bella',
  'Cahya',
  'Dian',
  'Dewa',
  'Elisa',
  'Fajar',
  'Fitri',
  'Gilang',
  'Hana',
  'Indra',
  'Indah',
  'Joko',
  'Kartika',
  'Kevin',
  'Lestari',
  'Michael',
  'Mega',
  'Nanda',
  'Novi',
  'Oktavia',
  'Pandu',
  'Putra',
  'Qori',
  'Rani',
  'Reza',
  'Rina',
  'Satria',
  'Sinta',
  'Teguh',
  'Tiara',
  'Umar',
  'Vina',
  'Wahyu',
  'Winda',
  'Yoga',
  'Yuni',
  'Zaki',
  'Aditya',
  'Anisa',
  'Bima',
  'Clara',
  'Daniel',
  'Eva',
  'Farhan',
  'Grace',
  'Hadi',
  'Irene',
  'Jessica',
  'Krisna',
  'Laras',
  'Made',
]
export const LAST_NAMES = [
  'Saputra',
  'Wijaya',
  'Santoso',
  'Pratama',
  'Kurniawan',
  'Hidayat',
  'Lestari',
  'Siregar',
  'Nasution',
  'Halim',
  'Gunawan',
  'Susanto',
  'Wibowo',
  'Putri',
  'Sihombing',
  'Tanoto',
  'Hartono',
  'Setiawan',
  'Rahayu',
  'Purnomo',
  'Utama',
  'Lim',
  'Kusuma',
  'Nugroho',
  'Fauzi',
  'Rahman',
  'Simanjuntak',
  'Firmansyah',
  'Prasetyo',
  'Wirawan',
]
export const CITIES: [string, number][] = [
  ['Jakarta', 30],
  ['Tangerang', 9],
  ['Bekasi', 8],
  ['Depok', 6],
  ['Bandung', 10],
  ['Surabaya', 10],
  ['Semarang', 5],
  ['Yogyakarta', 5],
  ['Medan', 5],
  ['Makassar', 4],
  ['Denpasar', 4],
  ['Balikpapan', 2],
  ['Palembang', 2],
]
export const AVATAR_COLORS = [
  '#4c5a78',
  '#6a5a8c',
  '#3f7a7b',
  '#7a5f4a',
  '#557a5c',
  '#8a5a6e',
  '#4f6f94',
  '#7a6b3f',
  '#5c5c7a',
  '#6b6f73',
]

export { DAY }
